-- V7: Add engagement fields to posts table for analytics dashboard
ALTER TABLE posts ADD COLUMN IF NOT EXISTS likes BIGINT DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS comments_count BIGINT DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS shares BIGINT DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reach BIGINT DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS engagement_synced_at TIMESTAMP;
